# Generated by Django 3.0.4 on 2020-03-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.EmailField(max_length=255, unique=True)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
